name: CI Checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint

  build_release_windows:
    env:
      GOOS: windows
      GOARCH: amd64
      TARGET: windows-amd64
      RELEASE_TAG: v0.3.2

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Create artifacts for window
        run: |
          go build -ldflags "-w -s -X main.VERSION=$RELEASE_TAG" -o bin/ergo.exe

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/ergo.exe
          asset_name: ergo-${{ env.TARGET }}.exe
          tag: ${{ env.RELEASE_TAG }}
          overwrite: true
