name: CI
on: [push]

env:
  PROJECT_NAME: ergo

jobs:
  tests:
    name: Linux
    env:
      GOOS: linux
      GOARCH: amd64
      TARGET: linux-amd64

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: make all
    - run: make coverage
    - run: make test
